// GENERATED by vgi.codegen.rust_registry. DO NOT EDIT BY HAND.
//
// Generator: python -m vgi.codegen.rust_registry v1
// Content hash: 1d384e1f7773
//
// To regenerate:
//   uv run --project ~/Development/vgi-python python scripts/regen_generated.py

// Copyright 2025, 2026 Query Farm LLC - https://query.farm

//! The `vgi.v2` registry (protocol version 2.1.0): the [`VgiService`] trait,
//! its `UNIMPLEMENTED` defaults, and [`register`], the table that hosts every
//! method on an [`RpcServer`] with the reference's params, result and header
//! schemas. Generated from vgi-python's `VgiProtocol`; the schemas are what
//! `vgi_rpc.Reflection.v1` hashes.

#![allow(clippy::too_many_lines)]

use std::sync::Arc;

use arrow_array::RecordBatch;
use arrow_schema::{DataType, Field, Fields, Schema, SchemaRef};
use vgi_rpc::stream::StreamStateKind;
use vgi_rpc::{
    CallContext, MethodInfo, MethodType, Request, Result, RpcError, RpcServer, StreamResult,
};

/// Every `vgi.v2` method's wire name, sorted.
pub const METHOD_NAMES: &[&str] = &[
    "aggregate_bind",
    "aggregate_combine",
    "aggregate_destructor",
    "aggregate_finalize",
    "aggregate_streaming_chunk",
    "aggregate_streaming_close",
    "aggregate_streaming_open",
    "aggregate_update",
    "aggregate_window",
    "aggregate_window_batch",
    "aggregate_window_destructor",
    "aggregate_window_init",
    "bind",
    "catalog_attach",
    "catalog_catalogs",
    "catalog_contents",
    "catalog_copy_from_formats",
    "catalog_create",
    "catalog_detach",
    "catalog_drop",
    "catalog_index_create",
    "catalog_index_drop",
    "catalog_index_get",
    "catalog_macro_create",
    "catalog_macro_drop",
    "catalog_macro_get",
    "catalog_schema_contents_functions",
    "catalog_schema_contents_indexes",
    "catalog_schema_contents_macros",
    "catalog_schema_contents_tables",
    "catalog_schema_contents_views",
    "catalog_schema_create",
    "catalog_schema_drop",
    "catalog_schema_get",
    "catalog_schemas",
    "catalog_table_column_add",
    "catalog_table_column_comment_set",
    "catalog_table_column_default_drop",
    "catalog_table_column_default_set",
    "catalog_table_column_drop",
    "catalog_table_column_rename",
    "catalog_table_column_statistics_get",
    "catalog_table_column_type_change",
    "catalog_table_comment_set",
    "catalog_table_create",
    "catalog_table_delete_function_get",
    "catalog_table_drop",
    "catalog_table_get",
    "catalog_table_insert_function_get",
    "catalog_table_not_null_drop",
    "catalog_table_not_null_set",
    "catalog_table_rename",
    "catalog_table_scan_branches_get",
    "catalog_table_scan_function_get",
    "catalog_table_update_function_get",
    "catalog_transaction_begin",
    "catalog_transaction_commit",
    "catalog_transaction_rollback",
    "catalog_version",
    "catalog_view_comment_set",
    "catalog_view_create",
    "catalog_view_drop",
    "catalog_view_get",
    "catalog_view_rename",
    "init",
    "table_buffering_combine",
    "table_buffering_destructor",
    "table_buffering_process",
    "table_function_cardinality",
    "table_function_dynamic_to_string",
    "table_function_plan",
    "table_function_statistics",
];

/// The error every [`VgiService`] default answers: `UNIMPLEMENTED` /
/// `method_not_implemented` with `"<method> is not implemented by this worker"`.
pub fn not_implemented(method: &str) -> RpcError {
    RpcError::method_not_implemented(format!("{method} is not implemented by this worker"))
}

/// The `vgi.v2` protocol: every method a VGI worker serves, generated from the
/// reference (`vgi.protocol.VgiProtocol` in vgi-python).
///
/// Every method has a default body answering `UNIMPLEMENTED` /
/// `method_not_implemented` with `"<method> is not implemented by this worker"`;
/// an implementation overrides the methods it serves. [`register`] hosts every
/// method, implemented or not, with the reference's schemas: the protocol is the
/// unit of optionality, and `vgi_rpc.Reflection.v1` reports one `vgi.v2` hash in
/// every SDK.
///
/// Each method receives the raw request, whose batch matches the method's params
/// schema (documented on the method), and returns the raw result batch. Never
/// change a signature or a schema here by hand: regenerate, so the change comes
/// from the protocol.
#[rustfmt::skip]
pub trait VgiService: Send + Sync + 'static {
    /// Bind an aggregate function, return output schema and execution_id.
    ///
    /// Wire method `aggregate_bind` (unary): params `(request: binary)`, result `result: binary`.
    /// Default: answers `UNIMPLEMENTED`.
    fn aggregate_bind(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_bind"))
    }

    /// Merge source states into target states.
    ///
    /// Wire method `aggregate_combine` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn aggregate_combine(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_combine"))
    }

    /// Best-effort cleanup of aggregate states. Must not raise.
    ///
    /// Wire method `aggregate_destructor` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn aggregate_destructor(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_destructor"))
    }

    /// Produce results for a chunk of group_ids.
    ///
    /// Wire method `aggregate_finalize` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn aggregate_finalize(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_finalize"))
    }

    /// Process one input chunk; returns one output row per input row.
    ///
    /// Wire method `aggregate_streaming_chunk` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn aggregate_streaming_chunk(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_streaming_chunk"))
    }

    /// End the streaming session, free per-session state.
    ///
    /// Wire method `aggregate_streaming_close` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn aggregate_streaming_close(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_streaming_close"))
    }

    /// Start a streaming-partitioned aggregate session.
    ///
    /// Wire method `aggregate_streaming_open` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn aggregate_streaming_open(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_streaming_open"))
    }

    /// Accumulate rows from a `DataChunk` into per-group state.
    ///
    /// Wire method `aggregate_update` (unary): params `(request: binary)`, result `result: binary`.
    /// Default: answers `UNIMPLEMENTED`.
    fn aggregate_update(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_update"))
    }

    /// Compute an aggregate value for one output row of the window.
    ///
    /// Wire method `aggregate_window` (unary): params `(request: binary)`, result `result: binary`.
    /// Default: answers `UNIMPLEMENTED`.
    fn aggregate_window(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_window"))
    }

    /// Compute `count` window output rows in one batched RPC.
    ///
    /// Wire method `aggregate_window_batch` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn aggregate_window_batch(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_window_batch"))
    }

    /// Evict a cached partition from storage.
    ///
    /// Wire method `aggregate_window_destructor` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn aggregate_window_destructor(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_window_destructor"))
    }

    /// Ship a partition to the worker for windowed aggregation.
    ///
    /// Wire method `aggregate_window_init` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn aggregate_window_init(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("aggregate_window_init"))
    }

    /// Resolve output schema and validate arguments.
    ///
    /// Wire method `bind` (unary): params `(request: binary)`, result `result: binary`. Default:
    /// answers `UNIMPLEMENTED`.
    fn bind(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("bind"))
    }

    /// Attach to a catalog with options.
    ///
    /// Wire method `catalog_attach` (unary): params `(request: binary)`, result `result: binary`.
    /// Default: answers `UNIMPLEMENTED`.
    fn catalog_attach(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_attach"))
    }

    /// List available catalog names.
    ///
    /// Wire method `catalog_catalogs` (unary): params `()`, result `result: binary`. Default:
    /// answers `UNIMPLEMENTED`.
    fn catalog_catalogs(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_catalogs"))
    }

    /// Return every schema and all of its contents in one result.
    ///
    /// Wire method `catalog_contents` (unary): params
    /// `(attach_opaque_data: binary, if_none_match: utf8?)`, result `result: binary`. Default:
    /// answers `UNIMPLEMENTED`.
    fn catalog_contents(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_contents"))
    }

    /// List custom `COPY ... FROM` formats advertised by this catalog.
    ///
    /// Wire method `catalog_copy_from_formats` (unary): params
    /// `(attach_opaque_data: binary, transaction_opaque_data: binary?)`, result `result: binary`.
    /// Default: answers `UNIMPLEMENTED`.
    fn catalog_copy_from_formats(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_copy_from_formats"))
    }

    /// Create a new catalog.
    ///
    /// Wire method `catalog_create` (unary): params `(request: binary)`, no result. Default:
    /// answers `UNIMPLEMENTED`.
    fn catalog_create(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_create"))
    }

    /// Detach from a catalog.
    ///
    /// Wire method `catalog_detach` (unary): params `(attach_opaque_data: binary)`, no result.
    /// Default: answers `UNIMPLEMENTED`.
    fn catalog_detach(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_detach"))
    }

    /// Drop a catalog.
    ///
    /// Wire method `catalog_drop` (unary): params `(name: utf8)`, no result. Default: answers
    /// `UNIMPLEMENTED`.
    fn catalog_drop(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_drop"))
    }

    /// Create a new index.
    ///
    /// Wire method `catalog_index_create` (unary): params `(request: binary)`, no result. Default:
    /// answers `UNIMPLEMENTED`.
    fn catalog_index_create(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_index_create"))
    }

    /// Drop an index.
    ///
    /// Wire method `catalog_index_drop` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, ignore_not_found: bool, cascade: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_index_drop(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_index_drop"))
    }

    /// Get information about an index. Returns 0 or 1 items.
    ///
    /// Wire method `catalog_index_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_index_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_index_get"))
    }

    /// Create a new macro.
    ///
    /// Wire method `catalog_macro_create` (unary): params `(request: binary)`, no result. Default:
    /// answers `UNIMPLEMENTED`.
    fn catalog_macro_create(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_macro_create"))
    }

    /// Drop a macro.
    ///
    /// Wire method `catalog_macro_drop` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_macro_drop(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_macro_drop"))
    }

    /// Get information about a macro. Returns 0 or 1 items.
    ///
    /// Wire method `catalog_macro_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_macro_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_macro_get"))
    }

    /// List functions in a schema (scalar or table).
    ///
    /// Wire method `catalog_schema_contents_functions` (unary): params
    /// `(attach_opaque_data: binary, path: list<utf8>, type: dictionary<int16, utf8>, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_schema_contents_functions(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_schema_contents_functions"))
    }

    /// List indexes in a schema.
    ///
    /// Wire method `catalog_schema_contents_indexes` (unary): params
    /// `(attach_opaque_data: binary, path: list<utf8>, transaction_opaque_data: binary?)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_schema_contents_indexes(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_schema_contents_indexes"))
    }

    /// List macros in a schema (scalar or table).
    ///
    /// Wire method `catalog_schema_contents_macros` (unary): params
    /// `(attach_opaque_data: binary, path: list<utf8>, type: dictionary<int16, utf8>, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_schema_contents_macros(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_schema_contents_macros"))
    }

    /// List tables in a schema.
    ///
    /// Wire method `catalog_schema_contents_tables` (unary): params
    /// `(attach_opaque_data: binary, path: list<utf8>, transaction_opaque_data: binary?)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_schema_contents_tables(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_schema_contents_tables"))
    }

    /// List views in a schema.
    ///
    /// Wire method `catalog_schema_contents_views` (unary): params
    /// `(attach_opaque_data: binary, path: list<utf8>, transaction_opaque_data: binary?)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_schema_contents_views(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_schema_contents_views"))
    }

    /// Create a new schema.
    ///
    /// Wire method `catalog_schema_create` (unary): params
    /// `(attach_opaque_data: binary, path: list<utf8>, on_conflict: dictionary<int16, utf8>, comment: utf8?, tags: map<utf8, utf8>?, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_schema_create(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_schema_create"))
    }

    /// Drop a schema.
    ///
    /// Wire method `catalog_schema_drop` (unary): params
    /// `(attach_opaque_data: binary, path: list<utf8>, ignore_not_found: bool, cascade: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_schema_drop(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_schema_drop"))
    }

    /// Get information about a schema. Returns 0 or 1 items.
    ///
    /// Wire method `catalog_schema_get` (unary): params
    /// `(attach_opaque_data: binary, path: list<utf8>, transaction_opaque_data: binary?)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_schema_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_schema_get"))
    }

    /// List schemas in the catalog.
    ///
    /// Wire method `catalog_schemas` (unary): params
    /// `(attach_opaque_data: binary, transaction_opaque_data: binary?)`, result `result: binary`.
    /// Default: answers `UNIMPLEMENTED`.
    fn catalog_schemas(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_schemas"))
    }

    /// Add a new column to a table.
    ///
    /// Wire method `catalog_table_column_add` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, column_definition: binary, ignore_not_found: bool, if_column_not_exists: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_column_add(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_column_add"))
    }

    /// Set or clear the comment on a table column.
    ///
    /// Wire method `catalog_table_column_comment_set` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, column_name: utf8, comment: utf8?, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_column_comment_set(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_column_comment_set"))
    }

    /// Remove the default value from a column.
    ///
    /// Wire method `catalog_table_column_default_drop` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, column_name: utf8, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_column_default_drop(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_column_default_drop"))
    }

    /// Set the default value expression for a column.
    ///
    /// Wire method `catalog_table_column_default_set` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, column_name: utf8, expression: utf8, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_column_default_set(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_column_default_set"))
    }

    /// Drop a column from a table.
    ///
    /// Wire method `catalog_table_column_drop` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, column_name: utf8, ignore_not_found: bool, if_column_exists: bool, cascade: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_column_drop(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_column_drop"))
    }

    /// Rename a column.
    ///
    /// Wire method `catalog_table_column_rename` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, column_name: utf8, new_column_name: utf8, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_column_rename(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_column_rename"))
    }

    /// Get column statistics for a table.
    ///
    /// Wire method `catalog_table_column_statistics_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, transaction_opaque_data: binary?)`,
    /// result `result: binary?`. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_column_statistics_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_column_statistics_get"))
    }

    /// Change the type of a column.
    ///
    /// Wire method `catalog_table_column_type_change` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, column_definition: binary, expression: utf8?, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_column_type_change(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_column_type_change"))
    }

    /// Set or clear the comment on a table.
    ///
    /// Wire method `catalog_table_comment_set` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, comment: utf8?, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_comment_set(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_comment_set"))
    }

    /// Create a new table.
    ///
    /// Wire method `catalog_table_create` (unary): params `(request: binary)`, no result. Default:
    /// answers `UNIMPLEMENTED`.
    fn catalog_table_create(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_create"))
    }

    /// Get the delete function for a table. Returns `WriteFunctionResult` as IPC bytes.
    ///
    /// Wire method `catalog_table_delete_function_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_delete_function_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_delete_function_get"))
    }

    /// Drop a table.
    ///
    /// Wire method `catalog_table_drop` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, ignore_not_found: bool, cascade: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_drop(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_drop"))
    }

    /// Get information about a table. Returns 0 or 1 items.
    ///
    /// Wire method `catalog_table_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, at_unit: utf8?, at_value: utf8?, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_get"))
    }

    /// Get the insert function for a table. Returns `WriteFunctionResult` as IPC bytes.
    ///
    /// Wire method `catalog_table_insert_function_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, transaction_opaque_data: binary?, writable_branch_function_name: utf8?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_insert_function_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_insert_function_get"))
    }

    /// Remove NOT NULL constraint from a column.
    ///
    /// Wire method `catalog_table_not_null_drop` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, column_name: utf8, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_not_null_drop(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_not_null_drop"))
    }

    /// Add NOT NULL constraint to a column.
    ///
    /// Wire method `catalog_table_not_null_set` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, column_name: utf8, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_not_null_set(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_not_null_set"))
    }

    /// Rename a table.
    ///
    /// Wire method `catalog_table_rename` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, new_name: utf8, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_rename(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_rename"))
    }

    /// Get the list of scan branches for a multi-branch table. Returns `ScanBranchesResult` as IPC
    /// bytes.
    ///
    /// Wire method `catalog_table_scan_branches_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, at_unit: utf8?, at_value: utf8?, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_scan_branches_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_scan_branches_get"))
    }

    /// Get the scan function for a table. Returns `ScanFunctionResult` as IPC bytes.
    ///
    /// Wire method `catalog_table_scan_function_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, at_unit: utf8?, at_value: utf8?, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_scan_function_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_scan_function_get"))
    }

    /// Get the update function for a table. Returns `WriteFunctionResult` as IPC bytes.
    ///
    /// Wire method `catalog_table_update_function_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_table_update_function_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_table_update_function_get"))
    }

    /// Begin a new transaction.
    ///
    /// Wire method `catalog_transaction_begin` (unary): params `(attach_opaque_data: binary)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_transaction_begin(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_transaction_begin"))
    }

    /// Commit a transaction.
    ///
    /// Wire method `catalog_transaction_commit` (unary): params
    /// `(attach_opaque_data: binary, transaction_opaque_data: binary)`, no result. Default: answers
    /// `UNIMPLEMENTED`.
    fn catalog_transaction_commit(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_transaction_commit"))
    }

    /// Rollback a transaction.
    ///
    /// Wire method `catalog_transaction_rollback` (unary): params
    /// `(attach_opaque_data: binary, transaction_opaque_data: binary)`, no result. Default: answers
    /// `UNIMPLEMENTED`.
    fn catalog_transaction_rollback(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_transaction_rollback"))
    }

    /// Get the current catalog version.
    ///
    /// Wire method `catalog_version` (unary): params
    /// `(attach_opaque_data: binary, transaction_opaque_data: binary?)`, result `result: binary`.
    /// Default: answers `UNIMPLEMENTED`.
    fn catalog_version(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_version"))
    }

    /// Set or clear the comment on a view.
    ///
    /// Wire method `catalog_view_comment_set` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, comment: utf8?, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_view_comment_set(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_view_comment_set"))
    }

    /// Create a new view.
    ///
    /// Wire method `catalog_view_create` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, definition: utf8, on_conflict: dictionary<int16, utf8>, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_view_create(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_view_create"))
    }

    /// Drop a view.
    ///
    /// Wire method `catalog_view_drop` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, ignore_not_found: bool, cascade: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_view_drop(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_view_drop"))
    }

    /// Get information about a view. Returns 0 or 1 items.
    ///
    /// Wire method `catalog_view_get` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, transaction_opaque_data: binary?)`,
    /// result `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn catalog_view_get(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_view_get"))
    }

    /// Rename a view.
    ///
    /// Wire method `catalog_view_rename` (unary): params
    /// `(attach_opaque_data: binary, schema_path: list<utf8>, name: utf8, new_name: utf8, ignore_not_found: bool, transaction_opaque_data: binary?)`,
    /// no result. Default: answers `UNIMPLEMENTED`.
    fn catalog_view_rename(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("catalog_view_rename"))
    }

    /// Initialize a function execution and return a processing stream.
    ///
    /// Wire method `init` (stream): params `(request: binary)`, headed by a `GlobalInitResponse`.
    /// Default: answers `UNIMPLEMENTED`.
    fn init(&self, _req: &Request, _ctx: &CallContext) -> Result<StreamResult> {
        Err(not_implemented("init"))
    }

    /// Rebuild a `init` stream's state from an HTTP continuation token (the bytes its
    /// state serialized to). Default: answers `UNIMPLEMENTED`.
    fn decode_init_state(&self, _state: &[u8]) -> Result<StreamStateKind> {
        Err(not_implemented("init"))
    }

    /// Once-per-query end-of-input signal. Returns finalize_state_ids.
    ///
    /// Wire method `table_buffering_combine` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn table_buffering_combine(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("table_buffering_combine"))
    }

    /// Best-effort end-of-query cleanup. Must not raise.
    ///
    /// Wire method `table_buffering_destructor` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn table_buffering_destructor(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("table_buffering_destructor"))
    }

    /// Sink one input batch; return the worker-chosen state_id.
    ///
    /// Wire method `table_buffering_process` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn table_buffering_process(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("table_buffering_process"))
    }

    /// Estimate the cardinality of a table function's output.
    ///
    /// Wire method `table_function_cardinality` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn table_function_cardinality(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("table_function_cardinality"))
    }

    /// Return user-defined diagnostics for EXPLAIN ANALYZE Extra Info.
    ///
    /// Wire method `table_function_dynamic_to_string` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn table_function_dynamic_to_string(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("table_function_dynamic_to_string"))
    }

    /// Plan a table-function scan into named, independently redeemable splits.
    ///
    /// Wire method `table_function_plan` (unary): params `(request: binary)`, result
    /// `result: binary`. Default: answers `UNIMPLEMENTED`.
    fn table_function_plan(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("table_function_plan"))
    }

    /// Return per-column statistics for a table function's output.
    ///
    /// Wire method `table_function_statistics` (unary): params `(request: binary)`, result
    /// `result: binary?`. Default: answers `UNIMPLEMENTED`.
    fn table_function_statistics(&self, _req: &Request, _ctx: &CallContext) -> Result<Option<RecordBatch>> {
        Err(not_implemented("table_function_statistics"))
    }
}

fn schema(fields: Vec<Field>) -> SchemaRef {
    Arc::new(Schema::new(fields))
}

/// Register every `vgi.v2` method on `srv`, each delegating to `svc`.
///
/// Methods `svc` does not override answer `UNIMPLEMENTED`, but are still
/// registered with their full schemas, so the protocol hash is the reference's.
#[rustfmt::skip]
pub fn register<S: VgiService>(srv: &mut RpcServer, svc: Arc<S>) {
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_bind",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_bind(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_combine",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_combine(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_destructor",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_destructor(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_finalize",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_finalize(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_streaming_chunk",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_streaming_chunk(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_streaming_close",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_streaming_close(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_streaming_open",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_streaming_open(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_update",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_update(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_window",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_window(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_window_batch",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_window_batch(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_window_destructor",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_window_destructor(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "aggregate_window_init",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.aggregate_window_init(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "bind",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.bind(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_attach",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_attach(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_catalogs",
            schema(vec![]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_catalogs(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_contents",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("if_none_match", DataType::Utf8, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_contents(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_copy_from_formats",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_copy_from_formats(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_create",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_create(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_detach",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_detach(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_drop",
            schema(vec![
                Field::new("name", DataType::Utf8, false),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_drop(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_index_create",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_index_create(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_index_drop",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("cascade", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_index_drop(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_index_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_index_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_macro_create",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_macro_create(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_macro_drop",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_macro_drop(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_macro_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_macro_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_schema_contents_functions",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("type", DataType::Dictionary(Box::new(DataType::Int16), Box::new(DataType::Utf8)), false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_schema_contents_functions(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_schema_contents_indexes",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_schema_contents_indexes(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_schema_contents_macros",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("type", DataType::Dictionary(Box::new(DataType::Int16), Box::new(DataType::Utf8)), false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_schema_contents_macros(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_schema_contents_tables",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_schema_contents_tables(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_schema_contents_views",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_schema_contents_views(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_schema_create",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("on_conflict", DataType::Dictionary(Box::new(DataType::Int16), Box::new(DataType::Utf8)), false),
                Field::new("comment", DataType::Utf8, true),
                Field::new("tags", DataType::Map(Arc::new(Field::new("entries", DataType::Struct(Fields::from(vec![Field::new("key", DataType::Utf8, false), Field::new("value", DataType::Utf8, true)])), false)), false), true),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_schema_create(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_schema_drop",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("cascade", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_schema_drop(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_schema_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_schema_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_schemas",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_schemas(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_column_add",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("column_definition", DataType::Binary, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("if_column_not_exists", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_column_add(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_column_comment_set",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("column_name", DataType::Utf8, false),
                Field::new("comment", DataType::Utf8, true),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_column_comment_set(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_column_default_drop",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("column_name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_column_default_drop(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_column_default_set",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("column_name", DataType::Utf8, false),
                Field::new("expression", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_column_default_set(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_column_drop",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("column_name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("if_column_exists", DataType::Boolean, false),
                Field::new("cascade", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_column_drop(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_column_rename",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("column_name", DataType::Utf8, false),
                Field::new("new_column_name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_column_rename(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_column_statistics_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, true),
            ]),
            move |req, ctx| s.catalog_table_column_statistics_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_column_type_change",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("column_definition", DataType::Binary, false),
                Field::new("expression", DataType::Utf8, true),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_column_type_change(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_comment_set",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("comment", DataType::Utf8, true),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_comment_set(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_create",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_create(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_delete_function_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_table_delete_function_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_drop",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("cascade", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_drop(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("at_unit", DataType::Utf8, true),
                Field::new("at_value", DataType::Utf8, true),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_table_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_insert_function_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
                Field::new("writable_branch_function_name", DataType::Utf8, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_table_insert_function_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_not_null_drop",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("column_name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_not_null_drop(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_not_null_set",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("column_name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_not_null_set(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_rename",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("new_name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_table_rename(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_scan_branches_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("at_unit", DataType::Utf8, true),
                Field::new("at_value", DataType::Utf8, true),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_table_scan_branches_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_scan_function_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("at_unit", DataType::Utf8, true),
                Field::new("at_value", DataType::Utf8, true),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_table_scan_function_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_table_update_function_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_table_update_function_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_transaction_begin",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_transaction_begin(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_transaction_commit",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("transaction_opaque_data", DataType::Binary, false),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_transaction_commit(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_transaction_rollback",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("transaction_opaque_data", DataType::Binary, false),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_transaction_rollback(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_version",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_version(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_view_comment_set",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("comment", DataType::Utf8, true),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_view_comment_set(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_view_create",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("definition", DataType::Utf8, false),
                Field::new("on_conflict", DataType::Dictionary(Box::new(DataType::Int16), Box::new(DataType::Utf8)), false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_view_create(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_view_drop",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("cascade", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_view_drop(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_view_get",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.catalog_view_get(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "catalog_view_rename",
            schema(vec![
                Field::new("attach_opaque_data", DataType::Binary, false),
                Field::new("schema_path", DataType::List(Arc::new(Field::new("item", DataType::Utf8, true))), false),
                Field::new("name", DataType::Utf8, false),
                Field::new("new_name", DataType::Utf8, false),
                Field::new("ignore_not_found", DataType::Boolean, false),
                Field::new("transaction_opaque_data", DataType::Binary, true),
            ]),
            schema(vec![]),
            move |req, ctx| s.catalog_view_rename(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        let d = svc.clone();
        let info = MethodInfo::stream(
            "init",
            MethodType::Dynamic,
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            move |req, ctx| s.init(req, ctx),
        )
        .with_state_decoder(Arc::new(move |state: &[u8]| d.decode_init_state(state)));
        let info = info.header_schema(schema(vec![
            Field::new("execution_id", DataType::Binary, false),
            Field::new("opaque_data", DataType::Binary, true),
            Field::new("max_workers", DataType::Int64, false),
        ]));
        srv.register(info);
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "table_buffering_combine",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.table_buffering_combine(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "table_buffering_destructor",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.table_buffering_destructor(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "table_buffering_process",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.table_buffering_process(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "table_function_cardinality",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.table_function_cardinality(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "table_function_dynamic_to_string",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.table_function_dynamic_to_string(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "table_function_plan",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, false),
            ]),
            move |req, ctx| s.table_function_plan(req, ctx),
        ));
    }
    {
        let s = svc.clone();
        srv.register(MethodInfo::unary(
            "table_function_statistics",
            schema(vec![
                Field::new("request", DataType::Binary, false),
            ]),
            schema(vec![
                Field::new("result", DataType::Binary, true),
            ]),
            move |req, ctx| s.table_function_statistics(req, ctx),
        ));
    }
}
